import type { ReportColumn, ReportRow } from "../types";
import type { User } from "../../../types";

export type AdminReportContext = {
  users: User[];
};

export type AdminReportDefinition = {
  id: string;
  title: string;
  description: string;
  columns: ReportColumn[];
  buildRows: (context: AdminReportContext, search: string, statusFilter: string) => ReportRow[];
};

function matchesSearch(values: (string | undefined)[], q: string) {
  if (!q) return true;
  const lq = q.toLowerCase();
  return values.some((v) => v?.toLowerCase().includes(lq));
}

export const ADMIN_REPORTS: AdminReportDefinition[] = [
  {
    id: "user-access-report",
    title: "User Access Report",
    description: "All system user accounts with role, department, school scope, and active status.",
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "role", label: "Role" },
      { key: "department", label: "Department" },
      { key: "schoolId", label: "School" },
      { key: "status", label: "Status" },
    ],
    buildRows: (context, search, statusFilter) =>
      context.users
        .filter((u) => {
          const matchStatus =
            statusFilter === "All" ||
            (statusFilter === "Active" ? u.isActive : !u.isActive);
          return matchStatus && matchesSearch([u.name, u.email, u.role, u.department], search);
        })
        .map((u) => ({
          id: u.id,
          name: u.name,
          email: u.email,
          role: u.role.replace(/_/g, " "),
          department: u.department || "—",
          schoolId: u.schoolId ?? "All Schools",
          status: u.isActive ? "Active" : "Inactive",
        })),
  },
  {
    id: "login-history",
    title: "Login History",
    description: "User login and session activity log. Requires session logging to be enabled.",
    columns: [
      { key: "user", label: "User" },
      { key: "role", label: "Role" },
      { key: "loginTime", label: "Login Time" },
      { key: "logoutTime", label: "Logout Time" },
      { key: "ipAddress", label: "IP Address" },
    ],
    buildRows: () => [],
  },
  {
    id: "activity-logs",
    title: "Activity Logs",
    description: "System activity and user action audit trail. Requires audit logging to be enabled.",
    columns: [
      { key: "user", label: "User" },
      { key: "action", label: "Action" },
      { key: "module", label: "Module" },
      { key: "timestamp", label: "Timestamp" },
    ],
    buildRows: () => [],
  },
  {
    id: "generated-reports-history",
    title: "Generated Reports History",
    description: "History of reports generated, exported, or printed. Requires report logging to be enabled.",
    columns: [
      { key: "reportName", label: "Report Name" },
      { key: "generatedBy", label: "Generated By" },
      { key: "exportType", label: "Export Type" },
      { key: "timestamp", label: "Timestamp" },
    ],
    buildRows: () => [],
  },
  {
    id: "data-export-history",
    title: "Data Export History",
    description: "History of CSV, Excel, and PDF data exports performed by users. Requires export logging to be enabled.",
    columns: [
      { key: "fileName", label: "File Name" },
      { key: "exportedBy", label: "Exported By" },
      { key: "exportType", label: "Export Type" },
      { key: "timestamp", label: "Timestamp" },
    ],
    buildRows: () => [],
  },
];
